package com.oreo.condition;

public enum ConditionType {
    VAULT_MONEY,
    OREO_CURRENCY,
    OREO_WARPS,
    OREO_WARPS_LOCATION,
    XP_LEVEL,
    XP_POINTS,
    ITEM,
    ITEM_CUSTOM_MODEL,
    ITEMSADDER,
    NEXO,
    PERMISSION,
    WORLDGUARD_REGION,
    PLACEHOLDER,
    WEATHER,
    WORLD,
    MODELED_NPC,
    LUCKPERMS_GROUP,
    EXPRESSION,
    PLACEHOLDER_EQUALS,
    PLACEHOLDER_CONTAINS,
    PLACEHOLDER_GREATER_THAN,
    PLACEHOLDER_LESS_THAN,
    SCRIPT
}
